import { Radar, User, Lock, Eye, Webhook, CalendarDays, MapPin, Users, Search, Heart, Clock, Tag, ChevronRight, Star, Zap, Music2, Laptop, Trophy, FileText, PlusCircle, X, CheckCircle, AlertCircle, DollarSign, Type, AlignLeft, Hash, Image as ImageIcon, ToggleLeft, ToggleRight } from "lucide-react-native"
export const ICONS = {
    radar: Radar,
    user: User,
    lock: Lock,
    eye: Eye,
    webhook: Webhook,
    CalendarDays: CalendarDays,
    MapPin: MapPin,
    Users: Users,
    Search: Search,
    Heart: Heart,
    Clock: Clock,
    Tag: Tag,
    ChevronRight: ChevronRight,
    Star: Star,
    Zap: Zap,
    Music2: Music2,
    Laptop: Laptop,
    Trophy: Trophy,
    FileText: FileText,
    PlusCircle: PlusCircle,
    X: X,
    CheckCircle: CheckCircle,
    AlertCircle: AlertCircle,
    DollarSign: DollarSign,
    Type: Type,
    AlignLeft: AlignLeft,
    Hash: Hash,
    ImageIcon: ImageIcon,
    ToggleLeft: ToggleLeft,
    ToggleRight: ToggleRight,
}