import { ICONS } from '@/components/icons';
import { Evento } from '../types';

export const C = {
    bg: '#F4F4FB',
    cardBg: '#FFFFFF',
    cardBorder: '#E9EAF4',
    accent: '#6366F1',          // uniradar-indigo
    accentLight: '#EEF2FF',
    accentPurple: '#A82BFA',
    accentCyan: '#22D3EE',
    accentGold: '#EAB308',
    green: '#22C55E',
    greenLight: '#DCFCE7',
    danger: '#EF4444',
    dangerLight: '#FEF2F2',
    textPrimary: '#111827',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    favActive: '#EC4899',
    tagBg: '#EEF2FF',
    tagText: '#4F46E5',
};

export const CATS: string[] = ['Todos', 'Tecnología', 'Música', 'Deporte', 'Social', 'Cultural'];

export const EVENTOS: Evento[] = [
    {
        id: '1',
        titulo: 'Hackathon Tech 2025',
        fecha: '24 Abr',
        hora: '09:00 AM',
        lugar: 'Centro de Convenciones, Lima',
        categoria: 'Tecnología',
        asistentes: 342,
        rating: 4.8,
        precio: 'Gratis',
        destacado: true,
        descripcion: 'El hackathon más grande del Perú. 48 horas de innovación, networking y premios increíbles.',
        imagenUri: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
        accentColor: C.accent,
        IconCategoria: ICONS.Laptop,
    },
    {
        id: '2',
        titulo: 'Festival Neon Beats',
        fecha: '02 May',
        hora: '07:00 PM',
        lugar: 'Anfiteatro del Parque, Miraflores',
        categoria: 'Música',
        asistentes: 1200,
        rating: 4.9,
        precio: 'S/ 80',
        destacado: true,
        descripcion: 'Una noche mágica con los mejores DJs del underground electrónico latinoamericano.',
        imagenUri: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
        accentColor: C.accentPurple,
        IconCategoria: ICONS.Music2,
    },
    {
        id: '3',
        titulo: 'Liga Universitaria eSports',
        fecha: '10 May',
        hora: '02:00 PM',
        lugar: 'Auditorio UTP, San Isidro',
        categoria: 'Deporte',
        asistentes: 580,
        rating: 4.6,
        precio: 'S/ 15',
        destacado: false,
        descripcion: 'Compite en League of Legends, Valorant y FIFA con los mejores equipos universitarios.',
        imagenUri: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
        accentColor: C.green,
        IconCategoria: ICONS.Trophy,
    },
    {
        id: '4',
        titulo: 'Workshop: React Native Pro',
        fecha: '18 May',
        hora: '10:00 AM',
        lugar: 'Online — Zoom',
        categoria: 'Tecnología',
        asistentes: 95,
        rating: 4.7,
        precio: 'S/ 45',
        destacado: false,
        descripcion: 'Aprende a construir apps móviles profesionales con React Native y Expo en 6 horas.',
        imagenUri: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80',
        accentColor: C.accentCyan,
        IconCategoria: ICONS.Zap,
    },
    {
        id: '5',
        titulo: 'Feria del Amor',
        fecha: '05 Mayo',
        hora: '17:00 PM',
        lugar: 'Plaza Central, Lima',
        categoria: 'Social',
        asistentes: 210,
        rating: 4.5,
        precio: 'Gratis',
        destacado: false,
        descripcion: 'Un espacio de encuentro, arte y experiencias sensoriales para conectar personas.',
        imagenUri: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80',
        accentColor: C.favActive,
        IconCategoria: ICONS.Heart,
    },
];
